platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: spring-boot-hello-world

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd spring-boot-hello-world
    mvn package
    cp ./target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar ../built-project/demo.jar