platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: hello-world

run:
  path: hello-world/ci/build.sh
    cp ./target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
