platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: hello-world

run:
  path: sh
  args:
  - -exc
  - |
    cd hello-world
    mvn package
    cp ./target/spring-boot-hello-world-1.0-SNAPSHOT.jar ../built-project/demo.jar
