platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "latest"
    

inputs:
- name: hello-world

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      cd hello-world
      mvn package
      
      cp ./target/spring-boot-hello-world-0.1-SNAPSHOT.jar ../built-project/demo.jar
