platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "latest"
    

inputs:
- name: hello-world

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      cd hello-world
      mvn package
      if [ -f ./target/spring-boot-hello-world-1.0-SNAPSHOT.jar ] ; then echo "yes, the .jar is there" ; else echo "no, it's not where expected" ; fi
      cd target
      ls pwd
      cd hello-world
