platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
- name: hello-world

run:
  path: sh
  args:
    - -exc
    - |
      cd spring-boot
      ./mvnw -f main clean install
      cp source-code/target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar  build-output/.
