platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: hello-world

run:
  path: sh
  args:
  - -exc
  - |
  ls
  pwd
  cd hello-world
  pwd
  ls
  mvn package
  cp ./target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
    
