platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "latest"
    

inputs:
- name: hello-world

run:
  path: sh
  args:
    - -exc
    - |
      cd hello-world
      mvn package
